runtime:
  cache_dir: ./.cache/antora

site:
  title: Solution Patterns from Red Hat
  url: https://solution.io
  start_page: solution-pattern::index.adoc
  keys:
    google_analytics: 'G-TKK0SMEFQH'  
  

content:
  sources:
    - url: ./
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-solution-patterns/course-ui/releases/download/v0.1.16/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
